swift:
  email:
    host: imap.gmail.com:993
    mailbox: INBOX
    username: [your email]
    password: [your password]
    poll-rate: 20000
reply:
  email:
    host: smtp.gmail.com
    port: 587
    username: [your email]
    password: [your password]